<!doctype html>
<html lang="ru">
<head>
  <?php include (__DIR__ . "/_/_head.phtml"); ?>

  <link href="/assets/css/family.css?<?=constant('HTML_VERSION');?>" rel="stylesheet">
</head>
<body>

<div id="body"
     class="body">
  <?php include (__DIR__ . "/_/_menu_header.phtml"); ?>

  <main class="b-layout"
        id="layout-family"
  >

    <!-- Шапка -->
    <div class="b-f-section b-f-section--default b-f-section--sm">
      <div class="container-offset content-light">
        <div class="container clearfix">
          <div class="b-f-section__container">

            <div class="b-f-section-header__grid">
              <div class="_text">
                <div class="b-f-section-header__content">

                  <div class="_blob">
                    <span class="b-f-blob b-f-blob--size--md b-f-blob--color--primary">
                      Новый сервис
                    </span>
                  </div>

                  <div class="_text">
                    <div class="b-content__cell">
                      <div class="_">

                        <div class="b-f-section-header__content-text">
                          <h1>
                            Электронное удостоверение
                            многодетной семьи
                          </h1>

                          <h3>
                            Доступен
                            <b>
                              с&nbsp;1&nbsp;октября 2024 года</b>
                          </h3>
                        </div>

                      </div>
                    </div>
                  </div>

                  <div class="_sub">
                    <div class="b-f-section-header__blockquote">
                      <div class="b-content__cell">
                        <div class="_">
                          <h5>
                            Сервис реализован в&nbsp;рамках федерального проекта
                            <br />
                            <b>&laquo;Государство для людей&raquo;</b>
                          </h5>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>
              </div>

              <div class="_img">
                <img src="/assets/img/family/img_family.png"
                     alt="" />

                <div class="b-f-section-header__sup">
                  <div class="b-content__cell">
                    <div class="_">
                      <p>
                        Интересы человека&nbsp;&mdash; приоритет для страны!
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Кто может -->
    <div class="b-f-section b-f-section--dark">
      <div class="container-offset content-dark">
        <div class="container clearfix">

          <div class="b-f-section-info__grid">
            <div class="_text">

              <div class="b-f-section__container">
                <div class="b-f-section-info__content-grid">
                  <div class="_text">
                    <div class="b-f-section__header">
                      <h2>
                        Кто может получить электронное удостоверение многодетной семьи?
                      </h2>
                    </div>

                    <div class="b-content__cell">
                      <div class="_">

                        <div class="b-f-section-info__content">
                          <h4>
                            Семьи, получившие статус многодетной семьи в&nbsp;соответствии с&nbsp;законодательством региона, в&nbsp;котором
                            проживают
                          </h4>
                        </div>

                      </div>
                    </div>
                  </div>

                  <div class="_sup">
                    <div class="b-f-section-info__info">
                      <div class="_img">
                        <i></i>
                      </div>

                      <div class="_text">
                        <div class="b-content__cell">
                          <div class="_">
                            <p>
                              Семья вправе использовать бумажную
                              или электронную версию удостоверения, либо обе
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>

            <div class="_img">
              <img src="/assets/img/family/img_phone.png"
                   alt="" />
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Преимущества -->
    <div class="b-f-section b-f-section--default">
      <div class="container-offset content-light">
        <div class="container clearfix">
          <div class="b-f-section__container">

            <div class="b-f-section__header">
              <h2>
                Преимущества электронного удостоверения:
              </h2>
            </div>

            <div class="b-f-section-adv__cell-primary">
              <div class="b-f-cell-grid b-f-cell-grid--2">
              <div class="_item">
                <div class="b-f-cell-grid__box b-f-cell-grid__box--dark b-f-cell-grid__box--sq">

                  <div class="b-f-section-adv__cell-primary-grid">
                    <div class="_img">
                      <div class="b-f-round-icon is--phone"></div>
                    </div>

                    <div class="_text">
                      <h6>
                        Мобильность и&nbsp;сохранность
                      </h6>

                      <p>
                        Удостоверение всегда под рукой, в&nbsp;Вашем смартфоне, можно
                        не&nbsp;переживать что вы&nbsp;забыли его дома, когда в&nbsp;нем есть необходимость, случайно
                        испортили или потеряли
                      </p>
                    </div>
                  </div>

                </div>
              </div>

              <div class="_item">
                <div class="b-f-cell-grid__box b-f-cell-grid__box--dark b-f-cell-grid__box--sq">
                  <div class="b-f-section-adv__cell-primary-grid">
                    <div class="_img">
                      <div class="b-f-round-icon is--heart"></div>
                    </div>

                    <div class="_text">
                      <h6>
                        Удобство совместного использования
                      </h6>

                      <p>
                        QR-кодом можно делится с&nbsp;другими членами семьи, бумажное удостоверение выдается только
                        в&nbsp;одном экземпляре на&nbsp;семью
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </div>

            <div class="b-f-section-adv__cell-secondary">
              <div class="b-f-cell-grid b-f-cell-grid--3">
              <div class="_item">
                <div class="b-f-cell-grid__box b-f-cell-grid__box--light">
                  <div class="b-content__cell">
                    <div class="_">
                      <div class="b-f-round-icon is--hand-heart"></div>

                      <p>
                        Всегда под рукой
                        в&nbsp;нужный момент
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div class="_item">
                <div class="b-f-cell-grid__box b-f-cell-grid__box--light">
                  <div class="b-content__cell">
                    <div class="_">
                      <div class="b-f-round-icon is--alert"></div>

                      <p>
                        Нельзя забыть, потерять, испортить
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div class="_item">
                <div class="b-f-cell-grid__box b-f-cell-grid__box--light">
                  <div class="b-content__cell">
                    <div class="_">
                      <div class="b-f-round-icon is--friends"></div>

                      <p>
                        Можно отправить другим членам семьи QR-код
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Как получить -->
    <div class="b-f-section b-f-section--dark">
      <div class="container-offset content-dark">
        <div class="container clearfix">
          <div class="b-f-section__container">

            <div class="b-f-section__header">

              <div class="b-f-section__header-grid--cls">
                <div class="_header">
                  <div class="b-content__cell">
                    <div class="_">

                      <h2>
                        Как получить и&nbsp;использовать электронное удостоверение?
                      </h2>

                    </div>
                  </div>
                </div>

                <div class="_line"></div>

                <div class="_sub">
                  <div class="b-content__cell">
                    <div class="_">
                      <p class="small">
                        Скидки в&nbsp;учреждениях культуры и&nbsp;другие меры поддержки от&nbsp;государства всегда &laquo;под
                        рукой&raquo; в&nbsp;вашем смартфоне
                      </p>
                    </div>
                  </div>
                </div>
              </div>

            </div>

            <div class="b-f-section-howto__cell">
              <div class="b-f-cell-grid b-f-cell-grid--3">
                <div class="_item">
                  <div class="b-f-cell-grid__box b-f-cell-grid__box--inverse">
                    <div class="b-content__cell">
                    <div class="_">
                      <div class="b-f-section-howto__cell-content">
                        <div class="_step">
                          <span class="b-f-blob b-f-blob--color--success">
                            Шаг&nbsp;1
                          </span>
                        </div>

                        <div class="_text">
                          <h6>
                            Заполнить заявление
                            на&nbsp;портале Госуслуг
                            <span>(если у&nbsp;вас нет статуса многодетности)</span>
                          </h6>

                          <p>
                            Решение по&nbsp;заявлению&nbsp;&mdash;
                            до&nbsp;10&nbsp;рабочих дней
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  </div>
                </div>

                <div class="_item">
                  <div class="b-f-cell-grid__box b-f-cell-grid__box--inverse">
                    <div class="b-content__cell">
                    <div class="_">
                      <div class="b-f-section-howto__cell-content">
                        <div class="_step">
                          <span class="b-f-blob b-f-blob--color--success">
                            Шаг&nbsp;2
                          </span>
                        </div>

                        <div class="_text">
                          <h6>
                            Получить электронное удостоверение на&nbsp;свое мобильное устройство
                          </h6>

                          <p>
                            Дав согласие в&nbsp;личном кабинете через мобильное приложение или через портал Госуслуг, только для
                            членов
                            многодетной семьи, кто имеет подтвержденную учетную запись ЕСИА
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  </div>
                </div>

                <div class="_item">
                  <div class="b-f-cell-grid__box b-f-cell-grid__box--inverse">
                    <div class="b-content__cell">
                    <div class="_">
                      <div class="b-f-section-howto__cell-content">
                        <div class="_step">
                          <span class="b-f-blob b-f-blob--color--success">
                            Шаг&nbsp;3
                          </span>
                        </div>

                        <div class="_text">
                          <h6>
                            Показать QR-код оказывающему услугу
                            для считывания
                            и&nbsp;идентификации статуса
                          </h6>

                          <p>
                            Оказывающий услугу считает QR-код и&nbsp;подтвердит актуальность статуса многодетной семьи
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="b-f-section-howto__btn">
              <a href="/assets/doc/family/manual-2024-10-04.pdf"
                 class="b-f-btn b-f-btn--color--outline-bg"
                 target="_blank">
                <span class="_cell">
                  <span class="_img">
                    <i class="_icon _icon--download"></i>
                  </span>
                  <span class="_text">
                    Скачать подробную инструкцию
                  </span>
                </span>
              </a>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Какие сведения -->
    <div class="b-f-section b-f-section--default">
      <div class="container-offset content-light">
        <div class="container clearfix">
          <div class="b-f-section__container">

            <div class="b-f-section__header">
              <h2>
                Какие сведения содержатся в&nbsp;электронном удостоверении многодетной семьи?
              </h2>
            </div>

            <div class="b-f-section-whats__cell-info">
              <div class="b-f-cell-grid b-f-cell-grid--4">
                <div class="_item">
                  <div class="b-f-cell-grid__box b-f-cell-grid__box--light">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-round-icon is--friends"></div>

                        <p>
                          Сведения о&nbsp;всех членах многодетной семьи
                          <span>(ФИО, дата рождения, СНИЛС)</span>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="_item">
                  <div class="b-f-cell-grid__box b-f-cell-grid__box--light">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-round-icon is--shield"></div>

                        <p>
                          Дата установления статуса многодетной семьи
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="_item">
                  <div class="b-f-cell-grid__box b-f-cell-grid__box--light">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-round-icon is--calendar"></div>

                        <p>
                          Срок предоставления мер поддержки
                          <span>(дата&nbsp;ДО какого числа/года)</span>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="_item">
                  <div class="b-f-cell-grid__box b-f-cell-grid__box--light">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-round-icon is--arms"></div>

                        <p>
                          Ответственное управление, выдавшее удостоверение
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="b-f-section-whats__ss">
              <div class="b-f-section-whats__ss-items">
                <div class="_item">
                  <img src="/assets/img/family/img_info-1.png"
                       alt="" />
                </div>

                <div class="_item">
                  <img src="/assets/img/family/img_info-2.png"
                       alt="" />
                </div>

                <div class="_item">
                  <img src="/assets/img/family/img_info-3.png"
                       alt="" />
                </div>
              </div>
            </div>

            <div class="b-f-section-whats__sub">
              <div class="_header">
                <div class="b-content__cell">
                  <div class="_">
                    <h3>
                      В&nbsp;чем отличия от&nbsp;бумажной версии?*
                    </h3>
                  </div>
                </div>
              </div>

              <div class="_cell">
                <div class="b-f-section-whats__cell-diff">
                  <div class="b-f-cell-grid b-f-cell-grid--3">
                    <div class="_item">
                      <div class="b-f-cell-grid__box b-f-cell-grid__box--dark">
                        <div class="b-content__cell">
                          <div class="_">
                            <div class="b-f-round-icon b-f-round-icon--sm is--heart"></div>

                            <p>
                              Можно пользоваться одновременно с&nbsp;другими членами семьи находясь в&nbsp;разных местах
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="_item">
                      <div class="b-f-cell-grid__box b-f-cell-grid__box--dark">
                        <div class="b-content__cell">
                          <div class="_">
                            <div class="b-f-round-icon b-f-round-icon--sm  b-f-round-icon--bg is--cloud"></div>

                            <p>
                              Невозможно потерять или забыть дома, нет необходимости восстанавливать
                              при утере
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="_item">
                      <div class="b-f-cell-grid__box b-f-cell-grid__box--dark">
                        <div class="b-content__cell">
                          <div class="_">
                            <div class="b-f-round-icon b-f-round-icon--sm is--qr"></div>

                            <p>
                              Быстрое подтверждение статуса многодетной семьи (оказывающий услугу сканирует QR-код)
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="_sub">
                <div class="b-content__cell">
                  <div class="_">
                    <p>
                      *Бумажная версия удостоверения продолжает иметь силу, в&nbsp;случае нежелания использования электронной
                    </p>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Проверка -->
    <div class="b-f-section b-f-section--light">
      <div class="container-offset content-dark">
        <div class="container clearfix">
          <div class="b-f-section__container">

            <div class="b-f-section__header">
              <h2>
                Проверка электронного удостоверения многодетной семьи
              </h2>

              <div class="b-f-section__header-grid--cb">
                <div class="_text">

                  <div class="b-content__cell">
                    <div class="_">

                      <p>
                        Как подтвердить статус в&nbsp;момент предъявления.
                        <br />
                        Действия проверяющего
                      </p>

                    </div>
                  </div>

                </div>
                <div class="_btn">

                  <a href="/assets/doc/family/manual-2024-10-04.pdf"
                     class="b-f-btn b-f-btn--color--outline"
                     target="_blank">
                    <span class="_cell">
                      <span class="_img">
                        <i class="_icon _icon--download"></i>
                      </span>
                      <span class="_text">
                        Скачать подробную инструкцию
                      </span>
                    </span>
                  </a>

                </div>
              </div>
            </div>

            <div class="b-f-section-check__steps">
              <div class="_item">
                <div class="b-f-section-check__item">
                  <div class="_img">
                    <img src="/assets/img/family/img_step-1.png"
                         alt=""
                    />
                  </div>
                  <div class="_text">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-section-check__item-content">
                          <div class="_step">
                            <span class="b-f-blob b-f-blob--color--success">
                              Шаг&nbsp;1
                            </span>
                          </div>

                          <div class="_text">
                            <h6>
                              Зайти в&nbsp;приложение Госуслуги с&nbsp;любого смартфона
                            </h6>

                            <p>
                              Авторизоваться в&nbsp;мобильном приложении с&nbsp;подтвержденной учетной записью
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="_item">
                <div class="b-f-section-check__item">
                  <div class="_img">
                    <img src="/assets/img/family/img_step-2.png"
                         alt=""
                    />
                  </div>
                  <div class="_text">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-section-check__item-content">
                          <div class="_step">
                            <span class="b-f-blob b-f-blob--color--success">
                              Шаг&nbsp;2
                            </span>
                          </div>

                          <div class="_text">
                            <h6>
                              Нажать на&nbsp;кнопку &laquo;Госкан&raquo;
                              в&nbsp;правом верхнем углу экрана
                            </h6>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="_item">
                <div class="b-f-section-check__item">
                  <div class="_img">
                    <img src="/assets/img/family/img_step-3.png"
                         alt=""
                    />
                  </div>
                  <div class="_text">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-section-check__item-content">
                          <div class="_step">
                            <span class="b-f-blob b-f-blob--color--success">
                              Шаг&nbsp;3
                            </span>
                          </div>

                          <div class="_text">
                            <h6>
                              Навести камеру устройства на&nbsp;QR-код удостоверения многодетной семьи, отображаемый на&nbsp;экране
                              смартфона гражданина
                            </h6>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="_item">
                <div class="b-f-section-check__item">
                  <div class="_img">
                    <img src="/assets/img/family/img_step-4.png"
                         alt=""
                    />
                  </div>
                  <div class="_text">
                    <div class="b-content__cell">
                      <div class="_">
                        <div class="b-f-section-check__item-content">
                          <div class="_step">
                            <span class="b-f-blob b-f-blob--color--success">
                              Шаг&nbsp;4
                            </span>
                          </div>

                          <div class="_text">
                            <h5>
                              Убедиться в&nbsp;успешном сканировании
                            </h5>

                            <p>
                              Откроется экран подтверждения статуса многодетной семьи с&nbsp;маскированными персональными данными
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Дополнительные возможности -->
    <div class="b-f-section b-f-section--default">
      <div class="container-offset content-light">
        <div class="container clearfix">
          <div class="b-f-section__container">

            <div class="b-f-section__header">
              <h2>
                Дополнительные возможности для поставщиков услуг для подтверждения статуса многодетности
              </h2>
            </div>

            <div class="b-content__cell">
              <div class="_">

                <div class="b-f-section-addons__list">
                  <ul>
                    <li>
                      <div class="b-f-section-addons__item">
                        <div class="b-f-section-addons__item-text">
                          <h3>
                            Федеральная витрина сведений о&nbsp;многодетных семьях
                          </h3>

                          <p>
                            <a href="https://lkuv.gosuslugi.ru/paip-portal/#/podd/datamarts/versions/243d5eba-3ba5-41c3-a373-b32e8afe2d17/card"
                               target="_blank">Ознакомиться с&nbsp;документацией</a>
                          </p>
                        </div>

                        <div class="b-f-section-addons__item-ready b-f-section-addons__item-ready--success">
                          <span class="_img">
                            <i></i>
                          </span>
                          <span class="_text">
                            Доступно для подключения
                          </span>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="b-f-section-addons__item">
                        <div class="b-f-section-addons__item-text">
                          <h3>
                            Делегированнное сканирование QR-кода удостоверения многодетного юридическим лицом через мобильное приложение Госуслуг
                          </h3>
                        </div>

                        <div class="b-f-section-addons__item-ready b-f-section-addons__item-ready--delay">
                          <span class="_img">
                            <i></i>
                          </span>
                          <span class="_text">
                            Будет доступно с&nbsp;1&nbsp;января 2025 года
                          </span>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="b-f-section-addons__item">
                        <div class="b-f-section-addons__item-text">
                          <h3>
                            API для получения данных юридическими лицами при считывании QR-кода удостоверения многодетного
                          </h3>

                          <p>
                            В&nbsp;том числе для считывания QR-кода сканерами касс
                          </p>
                        </div>

                        <div class="b-f-section-addons__item-ready b-f-section-addons__item-ready--delay">
                          <span class="_img">
                            <i></i>
                          </span>
                          <span class="_text">
                            Будет доступно с&nbsp;1&nbsp;января 2025 года
                          </span>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>

              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Интересы-->
    <div class="b-f-section b-f-section--light">
      <div class="container-offset content-dark">
        <div class="container clearfix">
          <div class="b-f-section__container">

            <div class="b-f-section__header">
              <h1>
                Интересы человека&nbsp;&mdash; приоритет для страны!
              </h1>
            </div>

            <div class="b-content__cell">
              <div class="_">

                <div class="b-f-section-interest__content">
                  <p>
                    При участии:
                  </p>
                </div>

                <div class="b-f-section-interest__link">
                  <div class="_item">
                    <a href="https://digital.gov.ru/"
                       target="_blank"
                       class="b-f-section-interest__btn"
                       title="Министерство цифрового развития, связи и массовых коммуникаций Российской Федерации"
                    >
                      <i class="b-f-section-interest__icon b-f-section-interest__icon-mc"></i>
                    </a>
                  </div>

                  <div class="_item">
                    <a href="https://mintrud.gov.ru/"
                       target="_blank"
                       class="b-f-section-interest__btn"
                       title="МИНИСТЕРСТВО ТРУДА И&nbsp;СОЦИАЛЬНОЙ ЗАЩИТЫ РОССИЙСКОЙ ФЕДЕРАЦИИ"
                    >
                      <i class="b-f-section-interest__icon b-f-section-interest__icon-mt"></i>
                    </a>
                  </div>

                  <div class="_item">
                    <a href="https://sfr.gov.ru/"
                       target="_blank"
                       class="b-f-section-interest__btn"
                       title="СОЦИАЛЬНЫЙ ФОНД РОССИИ"
                    >
                      <i class="b-f-section-interest__icon b-f-section-interest__icon-sf"></i>
                    </a>
                  </div>

                  <div class="_item">
                    <a href="https://ac.gov.ru/"
                       target="_blank"
                       class="b-f-section-interest__btn"
                       title="Аналитический центр при Правительстве Российской Федерации"
                    >
                      <i class="b-f-section-interest__icon b-f-section-interest__icon-ac"></i>
                    </a>
                  </div>
                </div>

              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </main>

  <?php include (__DIR__ . "/_/_footer.phtml"); ?>
</div>

<?php include (__DIR__ . "/_/_menu_fixed.phtml"); ?>

<?php include (__DIR__ . "/_/_menu_burger.phtml"); ?>

<?php include (__DIR__ . "/_/_menu_search.phtml"); ?>

<?php include (__DIR__ . "/_/_script.phtml"); ?>

</body>
</html>
