<div class="b-gallery"
     data-gallery-timeout="8000"
     data-gallery="true">
  <div class="b-gallery__items">
    <ul>
      <li class="active">
        <img src="/assets/img/about/photo_1.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_2.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_3.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_4.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_5.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_6.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_7.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_8.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_9.jpg" alt="" />
      </li>

      <li>
        <img src="/assets/img/about/photo_10.jpg" alt="" />
      </li>
    </ul>
  </div>

  <div class="b-gallery__control_arrow">
    <div class="_larr">
      <a href="javascript:;"
         data-gallery-control="left">
          <span class="b-btn_round">
            <i class="ic ic__larr"></i>
          </span>
      </a>
    </div>

    <div class="_rarr">
      <a href="javascript:;"
         data-gallery-control="right">
        <span class="b-btn_round">
          <i class="ic ic__rarr"></i>
        </span>
      </a>
    </div>
  </div>

  <!--
  <div class="b-gallery__control">
    <div class="b-gallery__control_cell">
      <div class="_row">

        <div class="_larr">
          <a href="javascript:;"
             data-gallery-control="left">
            <span class="b-btn_round">
              <i class="ic ic__larr"></i>
            </span>
          </a>
        </div>

        <div class="_text">
          <div class="b-gallery__control_text"
               style="display: none">
            <span data-gallery-current="">1</span>/<span data-gallery-total="">1</span>
          </div>
        </div>

        <div class="_rarr">
          <a href="javascript:;"
             data-gallery-control="right">
            <span class="b-btn_round">
              <i class="ic ic__rarr"></i>
            </span>
          </a>
        </div>

      </div>
    </div>
  </div>
  -->
</div>
