<header id="top">
  <div data-slide-container="true"
       data-slide="0"
       data-slide-timeout="0"
       class="b-header_index">
    <!-- -->
    <div class="b-header_index__bg">
      <div class="_item active"
           data-slide-bg="0"
           style="background-image: url(/assets/img/header_1.jpg);"></div>

      <div class="_item"
           data-slide-bg="1"
           style="background-image: url(/assets/img/vector_analytic_header.jpg);"></div>

      <div class="_item"
           data-slide-bg="2"
           style="background-image: url(/assets/img/vector_coordinate_header.jpg);"></div>

      <div class="_item"
           data-slide-bg="3"
           style="background-image: url(/assets/img/vector_gov_header.jpg);"></div>

      <div class="_item"
           data-slide-bg="4"
           style="background-image: url(/assets/img/vector_ai_header.jpg);"></div>

      <div class="_item"
           data-slide-bg="5"
           style="background-image: url(/assets/img/vector_national_header.jpg);"></div>

      <div class="_item"
           data-slide-bg="6"
           style="background-image: url(/assets/img/vector_reform_header.jpg);"></div>
    </div>

    <!-- -->
    <div class="container-offset content-dark">
      <div class="container">
        <div class="position-relative clearfix">

          <div class="b-header_index__video">
            <div class="_item enable active"
                 data-slide-video="0">
              <video src="/assets/video/07-dataman.mp4"
                     preload="auto"
                     autoplay="autoplay"
                     loop
                     muted></video>
            </div>

            <div class="_item"
                 data-slide-video="1">
              <video src="/assets/video/01-coordcenter.mp4"
                     preload="auto"
                     loop
                     muted></video>
            </div>

            <div class="_item"
                 data-slide-video="2">
              <video src="/assets/video/07-dataman.mp4"
                     preload="auto"
                     loop
                     muted></video>
            </div>

            <div class="_item"
                 data-slide-video="3">
              <video src="/assets/video/01-coordcenter.mp4"
                     preload="auto"
                     loop
                     muted></video>
            </div>

            <div class="_item"
                 data-slide-video="4">
              <video src="/assets/video/07-dataman.mp4"
                     preload="auto"
                     loop
                     muted></video>
            </div>

            <div class="_item"
                 data-slide-video="5">
              <video src="/assets/video/01-coordcenter.mp4"
                     preload="auto"
                     loop
                     muted></video>
            </div>

            <div class="_item"
                 data-slide-video="6">
              <video src="/assets/video/07-dataman.mp4"
                     preload="auto"
                     loop
                     muted></video>
            </div>
          </div>

          <div class="b-menu_nav__outer_container">
            <!-- -->
            <div class="b-header_index__slide">
              <!-- -->
              <div class="_item active"
                   data-slide-content="0">

                <div class="b-header_index__content">
                  <div>
                    <div class="_container">

                      <div class="b-header_index__text">
                        <h1>
                          Аналитический центр
                          <br />
                          при&nbsp;Правительстве
                          <br />
                          Российской&nbsp;Федерации
                        </h1>
                      </div>

                      <div class="b-header_index__search_form d-none d-sm-block">
                        <form method="get"
                              action="">

                          <div class="b-input block size-md color-default">
                            <div class="_cell">
                              <div class="_input">
                                <input type="text"
                                       name="q"
                                       placeholder="Поиск по сайту" />
                              </div>
                              <div class="_btn">
                                <a href="javascript:;"
                                   role="button"
                                   class="b-btn block size-md_input color-primary">
                                <span class="_cell">
                                  <span class="_text">
                                    Искать
                                  </span>
                                </span>
                                </a>
                              </div>
                            </div>
                          </div>

                        </form>
                      </div>

                    </div>
                  </div>
                </div>

              </div>

              <!-- -->
              <div class="_item"
                   data-slide-content="1">

                <div class="b-header_index__content">
                  <div>
                    <div class="_container">

                      <div class="b-header_index__text">
                        <h1>
                          Отраслевая
                          <br />
                          аналитика
                        </h1>

                        <p>
                          <a href="/"
                             class="b-btn size-md_index color-primary">
                            <span class="_cell">
                              <span class="_text">
                                Перейти
                              </span>
                            </span>
                          </a>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>

              </div>

              <!-- -->
              <div class="_item"
                   data-slide-content="2">

                <div class="b-header_index__content">
                  <div>
                    <div class="_container">

                      <div class="b-header_index__text">
                        <h1>
                          Координационный
                          <br />
                          центр
                        </h1>

                        <p>
                          <a href="/"
                             class="b-btn size-md_index color-primary">
                          <span class="_cell">
                            <span class="_text">
                              Перейти
                            </span>
                          </span>
                          </a>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>

              </div>

              <!-- -->
              <div class="_item"
                   data-slide-content="3">

                <div class="b-header_index__content">
                  <div>
                    <div class="_container">

                      <div class="b-header_index__text">
                        <h1>
                          Государство
                          <br />
                          для людей
                        </h1>

                        <p>
                          <a href="/"
                             class="b-btn size-md_index color-primary">
                            <span class="_cell">
                              <span class="_text">
                                Перейти
                              </span>
                            </span>
                          </a>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>

              </div>

              <!-- -->
              <div class="_item"
                   data-slide-content="4">

                <div class="b-header_index__content">
                  <div>
                    <div class="_container">

                      <div class="b-header_index__text">
                        <h1>
                          Искусственный
                          <br />
                          интеллект
                        </h1>

                        <p>
                          <a href="/"
                             class="b-btn size-md_index color-primary">
                            <span class="_cell">
                              <span class="_text">
                                Перейти
                              </span>
                            </span>
                          </a>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>

              </div>

              <!-- -->
              <div class="_item"
                   data-slide-content="5">

                <div class="b-header_index__content">
                  <div>
                    <div class="_container">

                      <div class="b-header_index__text">
                        <h1>
                          Национальные
                          <br />
                          проекты
                        </h1>

                        <p>
                          <a href="/"
                             class="b-btn size-md_index color-primary">
                            <span class="_cell">
                              <span class="_text">
                                Перейти
                              </span>
                            </span>
                          </a>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>

              </div>

              <!-- -->
              <div class="_item"
                   data-slide-content="6">

                <div class="b-header_index__content">
                  <div>
                    <div class="_container">

                      <div class="b-header_index__text">
                        <h1>
                          Реформа
                          <br />
                          КНД
                        </h1>

                        <p>
                          <a href="/"
                             class="b-btn size-md_index color-primary">
                            <span class="_cell">
                              <span class="_text">
                                Перейти
                              </span>
                            </span>
                          </a>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>

              </div>
            </div>

            <!-- -->
            <div class="b-slider_control__container">
              <div class="_larr">
                <a href="javascript:;"
                   data-slide-control="left">
                    <span class="b-btn_round">
                      <i class="ic ic__larr"></i>
                    </span>
                </a>
              </div>

              <div class="_dots">
                <div class="b-slider_control__dots">
                  <ul>
                    <li>
                      <a href="javascript:;"
                         data-slide-dot="0"
                         class="b-slider_control__progress">
                        <span></span>
                      </a>
                    </li>

                    <li>
                      <a href="javascript:;"
                         data-slide-dot="1"
                         class="b-slider_control__progress">
                        <span></span>
                      </a>
                    </li>

                    <li>
                      <a href="javascript:;"
                         data-slide-dot="2"
                         class="b-slider_control__progress">
                        <span></span>
                      </a>
                    </li>

                    <li>
                      <a href="javascript:;"
                         data-slide-dot="3"
                         class="b-slider_control__progress">
                        <span></span>
                      </a>
                    </li>

                    <li>
                      <a href="javascript:;"
                         data-slide-dot="4"
                         class="b-slider_control__progress">
                        <span></span>
                      </a>
                    </li>

                    <li>
                      <a href="javascript:;"
                         data-slide-dot="5"
                         class="b-slider_control__progress">
                        <span></span>
                      </a>
                    </li>

                    <li>
                      <a href="javascript:;"
                         data-slide-dot="6"
                         class="b-slider_control__progress">
                        <span></span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              <div class="_rarr">
                <a href="javascript:;"
                   data-slide-control="right">
                  <span class="b-btn_round">
                    <i class="ic ic__rarr"></i>
                  </span>
                </a>
              </div>
            </div>

            <!-- -->
            <div class="b-header_index__link">
              <ul>
                <li class="active">
                  <div>
                    <a href="">
                      Координационный центр
                    </a>
                  </div>
                </li>

                <li>
                  <div>
                    <a href="">
                      Государство для людей
                    </a>
                  </div>
                </li>

                <li>
                  <div>
                    <a href="">
                      Искусственный интеллект
                    </a>
                  </div>
                </li>

                <!-- -->

                <li>
                  <div>
                    <a href="">
                      Национальные проекты
                    </a>
                  </div>
                </li>

                <li>
                  <div>
                    <a href="">
                      Отраслевая аналитика
                    </a>
                  </div>
                </li>

                <li>
                  <div>
                    <a href="">
                      Управление данными
                    </a>
                  </div>
                </li>

                <!-- -->

                <li>
                  <div>
                    <a href="">
                      Реформа КНД
                    </a>
                  </div>
                </li>

                <li>
                  <div>
                    <a href="">
                      Проектный Олимп
                    </a>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- -->
    <div class="b-menu_nav__outer">
      <div class="container-offset content-dark">
        <div class="container clearfix">
          <?php $menuLight = true; ?>
          <?php $menuFull = false; ?>
          <?php include (__DIR__ . "/_menu_nav.phtml"); ?>

          <div class="b-menu_nav__outer_burger bg-dark"
               data-burger-wide="true">
            <div class="b-menu_nav__burger">
              <a href="javascript:;"
                 data-menu-over="#js-menu-burger">
                <i class="ic ic__burger"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
