<div id="js-menu-fixed"
     class="b-menu_fixed">
  <div class="container-offset content-light">
    <div class="container clearfix">
      <div class="b-menu_nav__container">

        <?php $menuLight = false; ?>
        <?php $menuFull = true; ?>
        <?php include (__DIR__ . "/_menu_nav.phtml"); ?>

      </div>
    </div>

    <div class="b-menu_nav__burger_wide">
      <div class="b-menu_nav__burger">
        <a href="javascript:;"
           data-menu-over="#js-menu-burger">
          <i class="ic ic__burger"></i></a>
      </div>
    </div>
  </div>
</div>
