<header id="top">
  <div class="b-menu_header">

    <div class="container-offset content-light">
      <div class="container clearfix">
        <div class="b-menu_header__container">

          <?php $menuLight = false; ?>
          <?php $menuFull = true; ?>
          <?php include (__DIR__ . "/_menu_nav.phtml"); ?>

        </div>

        <div class="b-menu_header__burger_wide bg-dark"
             data-burger-wide="true">
          <div class="b-menu_nav__burger">
            <a href="javascript:;"
               data-menu-over="#js-menu-burger">
              <i class="ic ic__burger"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
